version: '3.4'
services:
  redis:
    restart: always
    image: redis:4
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: '9511'
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - /home/core/db/redis.conf:/usr/local/etc/redis/redis.conf
      - '/home/core/db/redis:/data'
